# Generated by Django 5.1 on 2024-08-26 00:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_task_temp_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="id",
        ),
        migrations.AlterField(
            model_name="task",
            name="temp_uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, editable=False
            ),
        ),
        migrations.RenameField(
            model_name="task",
            old_name="temp_uuid",
            new_name="id",
        ),
    ]
