# Generated by Django 5.1 on 2024-08-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_task_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='task',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
